steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - rakuten-card-bqloader
      - --region=asia-northeast1
      - --source=.
      - --trigger-resource=rakuten-card-detail
      - --trigger-event=google.storage.object.finalize
      - --runtime=python39
      - --entry-point=bqloader
